version: "3.4"

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: emil@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emil
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testDb
    volumes:
      - pgvol:/var/lib/postgresql/data
  frontend:
    restart: always
    image: emilrasmussen/boligplatformen:frontend_$VERSION
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
        - "3001:5000"

volumes:
  pgvol:
  pgadmin:
